---
- hosts: all

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes
      become: yes
      tags:
      - jenkins

  roles:
    - environment-openjdk
    - ../environment-jenkins

  post_tasks:
    - name: Install avahi-daemon
      apt: pkg=avahi-daemon
      become: yes
      tags:
      - jenkins

    - name: Disable security
      lineinfile: dest=/var/lib/jenkins/config.xml regexp='<useSecurity>true</useSecurity>' line='<useSecurity>false</useSecurity>'
      tags:
      - jenkins
      notify: Restart Jenkins
      become: yes
