    - name: Add java 8 ppa
      apt_repository: repo="ppa:openjdk-r/ppa"
      tags:
      - jenkins
      - run
      become: yes

    - name: Install Jenkins key
      apt_key: url=https://pkg.jenkins.io/debian/jenkins.io.key state=present
      tags:
      - jenkins
      - run
      become: yes

    - name: Update source.list
      lineinfile: dest=/etc/apt/sources.list line="deb https://pkg.jenkins.io/debian binary/"
      tags:
      - jenkins
      - run
      become: yes

    - name: Update apt cache
      apt: update_cache=yes
      become: yes
      tags:
      - jenkins

    - name: Install java
      apt: pkg=openjdk-8-jre
      tags:
      - jenkins
      - run
      become: yes

    - name: Install Jenkins
      apt: pkg=jenkins
      tags:
      - jenkins
      - run
      notify:
      - Wait for Jenkins port to be available
      - Wait for Jenkins to be available
      - Store Jenkins CLI
      - Refresh jenkins update centre
      - Install Jenkins plugins
      become: yes

    - name: Update defaults
      lineinfile: dest=/etc/default/jenkins line='JAVA_ARGS="-Djenkins.install.runSetupWizard=false -Djava.awt.headless=true"' regexp='^JAVA_ARGS'
      tags:
      - jenkins
      - run
      become: yes

    - name: Restart Jenkins
      action: service name=jenkins state=restarted
      tags:
      - jenkins
      - run
      become: yes

    - name: No password sudo access for jenkins user
      lineinfile: "dest=/etc/sudoers state=present line='jenkins ALL=(ALL) NOPASSWD:ALL'"
      become: yes
